# Generated by Django 4.2.7 on 2024-10-23 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ownerfirst", models.CharField(max_length=200)),
                ("ownerlast", models.CharField(max_length=200)),
                ("siteaddres", models.CharField(max_length=200)),
                ("sitecity", models.CharField(blank=True, max_length=200, null=True)),
                ("sitezip", models.CharField(blank=True, max_length=200, null=True)),
                ("mailaddres", models.CharField(blank=True, max_length=200, null=True)),
                ("mailcity", models.CharField(blank=True, max_length=200, null=True)),
                ("mailstate", models.CharField(blank=True, max_length=200, null=True)),
                ("mzipandzip", models.CharField(blank=True, max_length=200, null=True)),
                ("bedrooms", models.CharField(blank=True, max_length=200, null=True)),
                ("bathtot", models.CharField(blank=True, max_length=200, null=True)),
                ("totalsf", models.CharField(blank=True, max_length=200, null=True)),
                ("lotsqft", models.CharField(blank=True, max_length=200, null=True)),
                ("landuse", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farm.farm"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
