# Generated by Django 4.2.7 on 2024-10-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="sitestate",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
